image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build:
  steps:
    - name: Grant execute permission for gradlew
        run: chmod +x gradlew

install:

  - java -jar ./artifacts/app-mbank.jar &

build_script:
  - ./gradlew test --info
